---
# tasks file for roles/change-user


- name: Include config.yml
  include_vars:
          file: ../files/config.yml

- name: Create User
  user:
          name: genesi nepo
          comment: Genesi Nepomuceno
          shell: /bin/bash
